### ISSUE TITLE
rgb2grayscale algorithm is not documented

### ISSUE THREAD

**Issue by benkasminbullock** [perlancar/perl-Color-RGB-Util#4]
The algorithm you're using to convert rgb to grayscale should be documented since there are different ones around. See for example this:

https://metacpan.org/pod/distribution/Image-PNG-Libpng/lib/Image/PNG/Libpng.pod#set_rgb_to_gray

**Comment by perlancar** [comment]
Sorry for the late response, didn't see the notification.

I've documented the algo and added `$algo` argument and provide the `weighted_average` alternative.

Ref: commit d36361c
